<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>kellenschmidt.com API</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin:0;
                padding:30px;
                font:14px Helvetica,Arial,Verdana,sans-serif;
            }
            h1 {
                margin:0 0 0.25rem;
                font-size:48px;
                font-weight:normal;
                line-height:48px;
            }
            #subtitle {
                font-size: 1.15rem;
                margin: 0 0 1.5rem;
            }
            img {
                margin: 1rem 0 2rem;
            }
        
        </style>
    </head>
    <body>
        <h1>Welcome to the kellenschmidt.com API</h1>
        <p id="subtitle">For interacting with the kellenschmidt.com database</p>
        <p>View the documentation on Apiary:</p>
        <a href="http://docs.kellensurlshortener.apiary.io/"><img src="images/apiary.png" width=300 id="apiary"></a>
        <p>View the project on GitHub:</p>
        <a href="https://github.com/kellenschmidt/urlshortener.kellenschmidt.com/"><img src="images/github.jpg" width=300 id="github"></a>
        <p>Go to Kellen's URL Shortener:</p>
        <a href="https://kellenschmidt.com/url"><img src="images/url-shortener.png" height=100 id="url-shortener"></a>
        <p>Go to Kellen's Personal Website:</p>
        <a href="https://kellenschmidt.com/"><img src="images/personal-website.png" height=100 id="personal-website"></a>
    </body>
</html>
